package com.miloud.englishstories

object Data {

    //Data Stories
    val stories = arrayOf(story("Story Title 1","Maecenas fringilla cursus est efficitur porta. Sed aliquam vestibulum felis, vel vestibulum dui euismod at. Pellentesque quis mi ut elit bibendum suscipit vitae in erat. Pellentesque ultrices mi nec purus mollis rhoncus. Nam imperdiet leo vel massa commodo tristique. Pellentesque eleifend malesuada tellus sed finibus. Praesent dui eros, pulvinar sed ipsum quis, tempor ullamcorper odio. Nam libero risus, dapibus quis eros at, ultricies vestibulum dolor. Quisque nisi neque, aliquet non sollicitudin eu, lacinia eu diam. Proin risus arcu, facilisis vel lacus sed, malesuada commodo leo. Cras in consectetur tortor. Suspendisse auctor, eros feugiat tempus maximus, nunc elit lobortis orci, sed iaculis tellus erat vitae massa. Nunc sed feugiat urna. Suspendisse vitae magna gravida, dapibus ante ac, ornare ante.\n" +
            "\n" +
            "Pellentesque laoreet enim sit amet libero laoreet, sed cursus dolor elementum. Suspendisse sit amet vestibulum odio. Morbi a nibh semper, mollis enim sit amet, aliquet sem. Etiam ac tellus metus. Aliquam eget tincidunt lorem. Mauris eleifend, nibh sit amet porttitor scelerisque, enim lorem pretium neque, id aliquam orci elit non elit. Vivamus gravida arcu eget nisl tristique tempus. Nulla elit velit, suscipit fringilla nunc eget, hendrerit aliquet nibh. Sed ut venenatis erat, sed ultricies magna. Cras venenatis malesuada faucibus. Donec ultrices placerat ex. Sed molestie cursus neque, sed condimentum nulla. Pellentesque suscipit, mi consectetur ullamcorper commodo, felis eros aliquam nunc, non fringilla sem nibh pellentesque elit. Vivamus condimentum semper mollis.\n" +
            "\n" +
            "Vestibulum facilisis vel tellus at egestas. Nam porttitor eleifend leo sit amet laoreet. Mauris tincidunt erat ut venenatis scelerisque. Aenean efficitur neque sit amet iaculis hendrerit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur quis efficitur sapien. Fusce eget felis risus. Vestibulum quis dolor condimentum, fringilla felis in, finibus magna. Aenean in ex tellus. Aliquam erat volutpat. Praesent ac ante cursus, finibus ligula a, sagittis felis. Phasellus dignissim vehicula tellus id ullamcorper. Aliquam non vestibulum nulla, non vulputate odio. Donec dignissim laoreet diam, sit amet dictum neque euismod efficitur.\n" +
            "\n" +
            "Nulla efficitur sapien et quam condimentum, eget tempus massa laoreet. Etiam id lacinia justo. Curabitur quis velit non velit egestas cursus. Curabitur posuere libero nulla, blandit vehicula velit ullamcorper sodales. Praesent mi purus, dictum ac porta vel, condimentum eget nulla. Pellentesque eget erat libero. Phasellus fringilla nisi at luctus varius. In hac habitasse platea dictumst. In id imperdiet ex, rutrum cursus magna.\n" +
            "\n" +
            "Fusce vitae vestibulum dolor. Nulla eu lacus pulvinar, ultricies ante sit amet, tempor lectus. Nullam tempus vel nisl vel volutpat. Morbi vitae nisl in mauris vehicula tempor quis vel lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed sit amet nisl et enim tempus hendrerit id eu augue. Vivamus sagittis magna eget sapien egestas, sed facilisis est mattis.\n" +
            "\n" +
            "Etiam eleifend ultrices turpis vitae viverra. Phasellus gravida massa at risus tristique, ut tristique lorem ullamcorper. Integer vitae tincidunt enim. Ut tincidunt arcu et aliquet faucibus. Nullam dapibus risus et tellus interdum tincidunt. Pellentesque tincidunt imperdiet ultrices. Aenean nec enim dolor. Quisque convallis nisi sed feugiat posuere. Sed ornare nulla quis justo lobortis accumsan. Sed sit amet lorem sit amet risus porta sollicitudin nec a nunc."),
                          story("Story Title 2","Praesent faucibus sapien id elit luctus, vitae efficitur lectus fermentum. Donec condimentum, est vitae maximus tincidunt, urna turpis interdum orci, sit amet gravida purus purus eget est. Nam ut cursus turpis, vel porttitor ante. Cras euismod neque lorem, eget pulvinar tortor blandit in. Duis mi lectus, convallis nec viverra non, laoreet quis ex. Maecenas volutpat urna sit amet urna mollis sagittis. Sed dictum ante sit amet arcu semper, eu condimentum tortor tincidunt. Sed id sapien vel massa venenatis tristique nec quis mauris. Pellentesque sed augue id ante sodales malesuada et a lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam ligula leo, cursus sit amet pulvinar eget, vehicula ac nibh. Nam sed nisi quis risus congue pretium. Cras arcu magna, tincidunt vel sodales vel, rhoncus eu lectus. Suspendisse ante quam, aliquet luctus dolor et, aliquet tincidunt odio. Aenean facilisis lacus urna, nec lobortis nulla semper efficitur. Morbi tempor sed ligula ut pharetra.\n" +
                                  "\n" +
                                  "Sed condimentum cursus eros vel vestibulum. Ut ultricies bibendum massa. Duis tincidunt mi quis interdum fringilla. Sed elit ex, porta eget urna in, consequat auctor enim. Nulla nisi dui, laoreet sed augue sit amet, hendrerit volutpat quam. Sed non nunc nisi. Integer placerat augue eget porttitor pharetra. Curabitur sodales, arcu in euismod laoreet, diam orci iaculis est, non bibendum orci sapien eget neque. Aenean malesuada facilisis neque vitae vehicula. Integer at vulputate tortor. Duis arcu purus, pellentesque eget lorem vitae, accumsan efficitur dolor. Praesent interdum porttitor enim quis blandit. Cras quis odio et lacus accumsan suscipit at nec dolor. Vestibulum auctor risus dignissim dapibus commodo. Aliquam ac interdum ipsum, et blandit purus.\n" +
                                  "\n" +
                                  "Mauris sollicitudin semper tempus. Donec lacinia arcu aliquet nisi hendrerit, sit amet ultrices magna varius. Suspendisse vel eros convallis, consectetur massa sit amet, pellentesque sem. Nullam rhoncus scelerisque ligula, ac eleifend ligula mattis cursus. Praesent placerat odio a nunc commodo, ac accumsan dolor molestie. Maecenas scelerisque lacus a tristique pharetra. Quisque sed consequat nisl, interdum molestie lorem. Etiam sodales dictum mattis.\n" +
                                  "\n" +
                                  "Proin pellentesque nunc in mi volutpat, sit amet dignissim augue dapibus. Nunc dictum pulvinar euismod. Aliquam gravida dictum massa, suscipit porta massa varius sit amet. Nullam nec ornare leo. Integer malesuada ullamcorper enim, ut interdum mauris auctor ut. Ut nisl turpis, euismod vel massa varius, aliquet euismod massa. Maecenas ac magna luctus, luctus metus a, pharetra ex. Duis auctor sagittis velit in pretium. Quisque ac lacus ac ipsum ultricies tempus mollis ac mauris. Sed auctor dui eu turpis rutrum tempus. Vestibulum a sem nec purus molestie scelerisque at et nulla. Donec non viverra tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent ullamcorper lobortis magna. Sed est augue, posuere sit amet lorem eget, volutpat venenatis nisl. Phasellus dapibus nunc eu lorem fringilla malesuada."),
                          story("Story Title 3","Nam nisi nisl, mattis id lorem sed, condimentum euismod enim. Donec malesuada nunc nisl, ut ultricies erat interdum quis. Etiam non lacus at massa mattis sagittis ac sit amet ipsum. Nulla sed nibh massa. Phasellus ut vestibulum dui. Vestibulum aliquet et ipsum quis vestibulum. Vestibulum laoreet felis ut ante tincidunt bibendum.\n" +
                                  "\n" +
                                  "Mauris eu ligula et nibh mollis ornare. Pellentesque et justo nec nisi tristique facilisis vel at enim. Nunc placerat pretium auctor. Nunc ut massa gravida, pretium neque vel, rhoncus diam. Nam eleifend sapien eget orci pellentesque, vitae tristique risus gravida. Praesent gravida magna felis, et tempor neque pulvinar pulvinar. Phasellus vitae urna et mauris aliquam tincidunt ut at nisi.\n" +
                                  "\n" +
                                  "Nunc eu nunc eget orci consectetur ultricies. Donec eu sapien justo. Praesent porttitor sapien viverra vestibulum elementum. Morbi nec arcu ligula. Fusce vitae mollis ligula. Vivamus pulvinar urna ut erat malesuada fringilla. Aliquam tempor semper augue sit amet aliquet. In eget nunc tristique, porta magna eget, congue ex. Nam varius feugiat purus, a aliquet risus elementum semper. Maecenas ac sapien a lacus egestas placerat vel vitae dolor."))
}